[ingestor]
# optional write path
# write_path = "./data/ingestor.mcap"

[parser]
# optional write path
# write_path = "./data/parser.mcap"

[ingestor.source]
# for reading from existing log
# read_path = "./data/ingestor.mcap"

# for reading from glidernet source
host = "aprs.glidernet.org"
port = 14580
filter = "r/0/0/250000000000"

[airspace]
time_buffer_seconds = 60
