---
name: CI
# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  PROTOC_VERSION: "34.0"
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # Skip rust-specific jobs to use caching from build step
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: rust-fmt,rust-clippy
  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all --check
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: ci-shared
      - uses: arduino/setup-protoc@v3
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo build --workspace --all-targets --all-features
  # ---- Depend on build; reuse its cache ----
  cargo-clippy:
    name: Cargo clippy
    needs: cargo-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache-shared-key: ci-shared
      - uses: arduino/setup-protoc@v3
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo clippy --workspace --all-targets --all-features
  cargo-doc:
    name: Cargo doc
    needs: cargo-build
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: ci-shared
      - uses: arduino/setup-protoc@v3
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo doc --workspace --all-features --no-deps
  cargo-next-test:
    name: Cargo test
    needs: cargo-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: ci-shared
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: arduino/setup-protoc@v3
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cargo nextest run \
          --workspace \
          --all-targets \
          --all-features \
          --no-tests=pass
